name: stock_pro
description: "StockPro - Smart Inventory Management System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ── State Management ──────────────────────────────────────
  provider: ^6.1.2

  # ── Local Storage ─────────────────────────────────────────
  shared_preferences: ^2.2.3

  # ── Utilities ─────────────────────────────────────────────
  intl: ^0.20.2
  equatable: ^2.0.5

  # ── Firebase Core ─────────────────────────────────────────
  firebase_core: ^4.9.0

  # ── Firebase Auth ─────────────────────────────────────────
  firebase_auth: ^6.5.1

  # ── Firebase Firestore ────────────────────────────────────
  cloud_firestore: ^6.4.1

  # ── Firebase Storage ──────────────────────────────────────
  firebase_storage: ^13.4.1

  # ── Part 6: Offline detection ─────────────────────────────
  connectivity_plus: ^6.0.0

  # ── Part 7: App version from pubspec ──────────────────────
  package_info_plus: ^8.0.0

  # ── Part 4: PDF receipt generation ───────────────────────
  pdf: ^3.11.0

  # ── Part 4: Print via system dialog ──────────────────────
  printing: ^5.12.0

  # ── Part 4: Share receipt — firebase_storage mime ^2.0.0 ─
  # share_plus ^9.0.0 mime ^1.0.4 se conflict karta tha
  # flutter ne khud suggest kiya: ^12.0.2 use karo
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true