// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5S6q2DGcBCKPWVGpyeKPfCj8zI3eIOmM',
    appId: '1:957704548097:web:b327376c32e82db6ec7500',
    messagingSenderId: '957704548097',
    projectId: 'stock-pro-1eb15',
    authDomain: 'stock-pro-1eb15.firebaseapp.com',
    storageBucket: 'stock-pro-1eb15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7cXbScgHdAIW94FGqm7jWFN-DjZz0x54',
    appId: '1:957704548097:android:2193be3eb61f5dbdec7500',
    messagingSenderId: '957704548097',
    projectId: 'stock-pro-1eb15',
    storageBucket: 'stock-pro-1eb15.firebasestorage.app',
  );
}